<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7LYrYAG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7LYrYAG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7LYrYAG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7LYrYAG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7LYrYAG\App_KernelDevDebugContainer([
    'container.build_hash' => '7LYrYAG',
    'container.build_id' => '3e28005f',
    'container.build_time' => 1670235862,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7LYrYAG');
