<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMgfHCXK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMgfHCXK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMgfHCXK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMgfHCXK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMgfHCXK\App_KernelDevDebugContainer([
    'container.build_hash' => 'MgfHCXK',
    'container.build_id' => 'db5afe9c',
    'container.build_time' => 1665579333,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMgfHCXK');
