<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9HlDxiN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9HlDxiN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9HlDxiN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9HlDxiN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9HlDxiN\App_KernelDevDebugContainer([
    'container.build_hash' => '9HlDxiN',
    'container.build_id' => 'b496e615',
    'container.build_time' => 1665391983,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9HlDxiN');
