controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# vychozi controller a akce
#welcome:
#    path:     /
#    controller: App\Controller\WelcomeController::index
